name: SonarQube Analysis & Unit Tests

on: push

jobs:
  sonar_analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17 # version 11 in the course was outdated and caused an error.
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'  # Ensure 'temurin' is the correct and supported distribution
          cache: maven  # This is correct for caching Maven packages

      - name: Build with Maven
        run: mvn -B verify sonar:sonar -Dsonar.projectKey=zaj_project -Dsonar.organization=saas-zaj -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=${{ secrets.SONAR_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
